// $Id: rootlogon.C 2637 2006-03-06 23:53:38Z loizides $

{
   // mit styles
   gStyle->SetErrorX(0);
   gStyle->SetPalette(1,0);
   gStyle->SetPadColor(0);
   gStyle->SetPadBorderSize(0);
   gStyle->SetPadBorderMode(0);
   gStyle->SetCanvasColor(0);
   gStyle->SetCanvasBorderMode(0);
   gStyle->SetCanvasBorderSize(0);
   gStyle->SetFrameBorderMode(0);
   gStyle->SetFrameLineColor(0);
   //gStyle->SetTitleColor(0);
   gStyle->SetTitleBorderSize(0); 
   gStyle->SetPalette(1,0); 
   gStyle->SetPadTickX(1);
   gStyle->SetPadTickY(1);
   gStyle->SetPadColor(0);
   gStyle->SetPadBorderSize(0);
   gStyle->SetPadBorderMode(0);
   gStyle->SetCanvasColor(0);
   gStyle->SetCanvasBorderMode(0);
   gStyle->SetCanvasBorderSize(0);
   gStyle->SetFrameBorderMode(0);
   gStyle->SetFrameLineColor(0);
   gStyle->SetTextFont(62);
   gStyle->SetLabelFont(42,"XYZ");
   gStyle->SetTitleFont(42,"XYZ");
   //gStyle->SetTitleColor(0);
   gStyle->SetTitleBorderSize(0);
   gStyle->SetTitleXSize(.055);
   gStyle->SetTitleYSize(.055);
   gStyle->SetTitleXOffset(1.0);
   gStyle->SetTitleYOffset(1.3);
   gStyle->SetLabelSize(0.045,"XYZ");
   gStyle->SetLabelOffset(0.01,"X");
   gStyle->SetLabelOffset(0.01,"Y");
   //gStyle->SetTitleColor(1,"XYZ");
   gStyle->SetHistFillColor(1);
   gStyle->SetHistFillStyle(0);
   gStyle->SetHistLineColor(1);
   gStyle->SetHistLineStyle(0);
   gStyle->SetHistLineWidth(3);
   gStyle->SetHistLineWidth(1);
   gStyle->SetEndErrorSize(0);
   gStyle->SetErrorX(0);  
   //gStyle->SetMarkerStyle(20);
   gStyle->SetMarkerStyle(1);
   gStyle->SetMarkerSize(1);
   gStyle->SetOptFit(0);
   //gStyle->SetOptFit(1111);
   gStyle->SetStatColor(0);
   gStyle->SetStatBorderSize(1);
   gStyle->SetStatFontSize(0.02);
   //gStyle->SetOptStat(1111);
   //gStyle->SetOptStat(0);

   // my options
   gStyle->SetPadLeftMargin(0.17);
   gStyle->SetPadRightMargin(0.17);
   gStyle->SetPadBottomMargin(0.17);
   //gStyle->SetPadTopMargin(0.05);
   gStyle->SetPadTopMargin(0.17);

   gStyle->SetNdivisions(6);
   gStyle->SetTitleXSize(.05);
   gStyle->SetTitleYSize(.04);
   gStyle->SetTitleXOffset(1.2);
   gStyle->SetTitleYOffset(1.4);
}
