#!/usr/bin/perl

print "\n===============================================";
print "\nConfigure the StorageManager (SM)...";
print "\n===============================================";
my $result = `curl --stderr /dev/null -H "SOAPAction: urn:xdaq-application:lid=4" -d @/export/04a/frankma/cmssw/modCMSSW_2_1_11/src/EventFilter/AutoBU/playback/workflowBase/mc_injection/mc217ModConfigure/soap/ConfigureSM.xml http://svmit04:40001`;
print "\n$result\n\n";

`sleep 1`;

print "\n===============================================";
print "\nConfigure the evf::FUEventProcessor (PB)...";
print "\n===============================================";
my $result = `curl --stderr /dev/null -H "SOAPAction: urn:xdaq-application:lid=4" -d @/export/04a/frankma/cmssw/modCMSSW_2_1_11/src/EventFilter/AutoBU/playback/workflowBase/mc_injection/mc217ModConfigure/soap/ConfigurePB.xml http://svmit04:40000`;
print "\n$result\n\n";

`sleep 30`;

print "\n===============================================";
print "\nEnable the evf::FUEventProcessor (PB)...";
print "\n===============================================";
my $result = `curl --stderr /dev/null -H "SOAPAction: urn:xdaq-application:lid=4" -d @/export/04a/frankma/cmssw/modCMSSW_2_1_11/src/EventFilter/AutoBU/playback/workflowBase/mc_injection/mc217ModConfigure/soap/EnablePB.xml http://svmit04:40000`;
print "\n$result\n\n";

`sleep 5`;

print "\n===============================================";
print "\nConfigure the evf::BU (BU)...";
print "\n===============================================";
my $result = `curl --stderr /dev/null -H "SOAPAction: urn:xdaq-application:lid=4" -d @/export/04a/frankma/cmssw/modCMSSW_2_1_11/src/EventFilter/AutoBU/playback/workflowBase/mc_injection/mc217ModConfigure/soap/ConfigureBU.xml http://svmit04:40000`;
print "\n$result\n\n";

print "\n===============================================";
print "\nConfigure the evf::FUResourceBroker (RB)...";
print "\n===============================================";
my $result = `curl --stderr /dev/null -H "SOAPAction: urn:xdaq-application:lid=4" -d @/export/04a/frankma/cmssw/modCMSSW_2_1_11/src/EventFilter/AutoBU/playback/workflowBase/mc_injection/mc217ModConfigure/soap/ConfigureRB.xml http://svmit04:40000`;
print "\n$result\n\n";

print "\n===============================================";
print "\nConfigure the evf::FUEventProcessor (EP0)...";
print "\n===============================================";
my $result = `curl --stderr /dev/null -H "SOAPAction: urn:xdaq-application:lid=4" -d @/export/04a/frankma/cmssw/modCMSSW_2_1_11/src/EventFilter/AutoBU/playback/workflowBase/mc_injection/mc217ModConfigure/soap/ConfigureEP0.xml http://svmit04:40002`;
print "\n$result\n\n";

