cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/rootlogon.C .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/dijetAna.h .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/plotJetLeading.C .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/plotFF.C .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/plotFinal.C .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/runJetAnaBase.sh .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/runGenericJetAnaPt.sh .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/run3JetAna_PtScan.sh .
cp /net/hisrv0001/home/frankma/work/hiroot/test/dijet/jetana/runAna/run3JetAna_PtScanPyquen.sh .
