TCanvas *c = new TCanvas("c","",600,600)
h->Draw("e")
nt->Draw("(gausMean+1.385409)/gausErr>>h(100,-5,5)")
h->Draw("e")
h->Fit("gaus")
h->SetMarkerStyle(4)
h->SetMarkerColor(2)
h->Fit("gaus")
h->Sumw2()
h->Fit("gaus")
h->SetLineColor(2)
h->Fit("gaus")
h->SetTitle("")
h->SetXTitle("mpt-<mpt>")
h->SetXTitle("(mpt-<mpt>)/#simga(mpt)")
h->SetXTitle("(mpt-<mpt>)/#sigma(mpt)")
h->SetYTitle("# of pseudo-exp")
c->SaveAs("
c->SaveAs("pseudoexp-mptx-data.gif
c->SaveAs("pseudoexp-mptx-data.gif")
