void print_cone(const char * infile) {
  TFile inf(infile);
  cout << " Info for " << infile << endl;
  cout << endl;
  cout << "========== Data =========" << endl;
  cout << "Average # of tracks in cone5:" << endl;
  cout << "  Near: " << hNCone5NP->GetMean() << endl;
  cout << "  Awayay: " << hACone5NP->GetMean() << endl;
  cout << "Average # of tracks in trans. cone5" << endl;
  cout << "  av:   " << hCone5NPBg->GetMean() << endl;
  cout << "Average # of signal tracks in cone5:" << endl;
  cout << "  Near: " << hNCone5NP->GetMean() - hCone5NPBg->GetMean() << endl;
  cout << "  Awayay: " << hACone5NP->GetMean() - hCone5NPBg->GetMean() << endl;
  cout << endl;
  cout << "Raw Xi Area:" << endl;
  cout << "  Near: " << hXiRaw_dataNear->Integral()*hXiRaw_dataNear->GetBinWidth(1) << endl;
  cout << "  Awayay: " << hXiRaw_dataAway->Integral()*hXiRaw_dataAway->GetBinWidth(1) << endl;
  cout << "Bkg Xi Area:" << endl;
  cout << "  Near: " << hXiBkg_dataNear->Integral()*hXiBkg_dataNear->GetBinWidth(1) << endl;
  cout << "  Awayay: " << hXiBkg_dataAway->Integral()*hXiBkg_dataAway->GetBinWidth(1) << endl;
  cout << "Sig Xi Area:" << endl;
  cout << "  Near: " << hXiSig_dataNear->Integral()*hXiSig_dataNear->GetBinWidth(1) << endl;
  cout << "  Awayay: " << hXiSig_dataAway->Integral()*hXiSig_dataAway->GetBinWidth(1) << endl;
  cout << endl
    << endl;
  cout << "========== MC =========" << endl;
  cout << "Average # of tracks in cone5:" << endl;
  cout << "  Near: " << h2NCone5NP->GetMean() << endl;
  cout << "  Awayay: " << h2ACone5NP->GetMean() << endl;
  cout << "Average # of tracks in trans. cone5" << endl;
  cout << "  av:   " << h2Cone5NPBg->GetMean() << endl;
  cout << "Average # of signal tracks in cone5:" << endl;
  cout << "  Near: " << h2NCone5NP->GetMean() - hCone5NPBg->GetMean() << endl;
  cout << "  Awayay: " << h2ACone5NP->GetMean() - hCone5NPBg->GetMean() << endl;
  cout << endl;
  cout << "Raw Xi Area: " << endl;
  cout << "  Near: " << hXiRaw_mcNear->Integral()*hXiRaw_mcNear->GetBinWidth(1) << endl;
  cout << "  Awayay: " << hXiRaw_mcAway->Integral()*hXiRaw_mcAway->GetBinWidth(1) << endl;
  cout << "Bkg Xi Area: " << endl;
  cout << "  Near: " << hXiBkg_mcNear->Integral()*hXiBkg_mcNear->GetBinWidth(1) << endl;
  cout << "  Awayay: " << hXiBkg_mcAway->Integral()*hXiBkg_mcAway->GetBinWidth(1) << endl;
  cout << "Sig Xi Area: " << endl;
  cout << "  Near: " << hXiSig_mcNear->Integral()*hXiSig_mcNear->GetBinWidth(1) << endl;
  cout << "  Awayay: " << hXiSig_mcAway->Integral()*hXiSig_mcAway->GetBinWidth(1) << endl;
}
